# Generated by Django 3.0 on 2019-12-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(max_length=120)),
                ('secondname', models.CharField(max_length=120)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('phonenumber', models.CharField(max_length=120, unique=True)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
