apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-db
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-db
        image: postgres:alpine
        ports:
        - containerPort: 6379
          name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: azure-db
spec:
  ports:
  - port: 5432
  selector:
    app: azure-db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-brb-backend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-brb-backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-brb-backend
        image: buyrentbungoma.azurecr.io/bungomaplus_web:v3
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: azure-brb-backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-brb-backend