# Generated by Django 3.0 on 2020-01-29 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1500)),
                ('image', models.CharField(max_length=500)),
                ('ad_ispaidfor', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('division', models.CharField(max_length=150, null=True)),
                ('ward', models.CharField(max_length=150, null=True)),
                ('locality', models.CharField(max_length=150, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('type_image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.Property')),
                ('gender_exclusive', models.BooleanField(default=False)),
                ('self_contained', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('meals', models.BooleanField(default=False)),
            ],
            bases=('properties.property',),
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.Property')),
                ('for_sale', models.BooleanField(default=True)),
                ('land_size', models.FloatField()),
            ],
            bases=('properties.property',),
        ),
        migrations.CreateModel(
            name='OfficeSpace',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.Property')),
                ('square_feet', models.FloatField()),
                ('internet', models.BooleanField(default=True)),
            ],
            bases=('properties.property',),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.Property')),
                ('rooms', models.PositiveIntegerField()),
                ('water', models.BooleanField(default=False)),
            ],
            bases=('properties.property',),
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.Property')),
            ],
            bases=('properties.property',),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.PropertyType'),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('title', 'owner', 'property_type')},
        ),
    ]
