# Generated by Django 3.0 on 2020-01-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='division',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='locality',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='ward',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='division',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='locality',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='ward',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='officespace',
            name='division',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='officespace',
            name='locality',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='officespace',
            name='ward',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='division',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='locality',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='ward',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='division',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='locality',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='ward',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
